# Generated by Django 4.1.3 on 2022-11-23 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_cliente_birth_date_alter_empresa_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='rg',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True),
        ),
    ]
